services:
  jade-dev:
#    restart: always
    build:
      context: .
    container_name: jade-dev
    volumes:
      - ./development.env:/app/.env
    working_dir: /app
    entrypoint: ["./Jade"]

  jade-prod:
    restart: always
    build:
      context: .
    container_name: jade-prod
    volumes:
      - ./production.env:/app/.env
    working_dir: /app
    entrypoint: ["./Jade"]